### ISSUE TITLE
Suggestion - add ver / version

### ISSUE THREAD

**Issue by premanshup** [commitizen/conventional-commit-types#14]
Sometimes we commit with just the version change. I think just changing version number does not fall under either `fix` or `feat`. So I feel like we should have a separate `ver` for just version changes?

**Comment by MarkWithall** [comment]
We use `release` for a version change, as the two tend to coincide.

**Comment by premanshup** [comment]
@MarkWithall Thank you for the suggestion but looking at the JSON file https://github.com/commitizen/conventional-commit-types/blob/master/index.json I did not find `release` anywhere. Are there any plans of adding `release` in the check?

**Comment by MarkWithall** [comment]
I've seen others use `chore(release)` (e.g. https://github.com/matatk/landmarks/commits/master), so it's possible that our use of `release` comes from a mis-translation of that. There's a certain sense in keeping the set of types minimal.

**Comment by premanshup** [comment]
@MarkWithall I see, we can use something similar to the eg which you have shared. Thank you! I'm closing this issue.

**Comment by AndersDJohnson** [comment]
Yes, `chore(version):` or `chore(release)` is recommended here.
