### ISSUE TITLE
Rename improvement to improv or similar

### ISSUE THREAD

**Issue by NathanUrwin** [commitizen/conventional-commit-types#15]
Improvement is kind of long... we're truncating feature to feat, so why not improvement to improv?

**Comment by AndersDJohnson** [comment]
@NathanUrwin I totally agree with you, but it's what is suggested on the official Conventional Commits spec now, so many people and teams are using it, so we're trying to align with that. I would encourage and support a proposal to have them change the spec though.

**Comment by AndersDJohnson** [comment]
@NathanUrwin It looks like they removed `improvement` as recommended. It was [in their `1.0.0-beta.4` release](https://github.com/conventional-commits/conventionalcommits.org/blame/a3f54496f57dfaf831447e21cd4c43a9cd7fc84e/content/v1.0.0-beta.4/index.md#L39), but [removed in `1.0.0`](https://github.com/conventional-commits/conventionalcommits.org/blame/a3f54496f57dfaf831447e21cd4c43a9cd7fc84e/content/v1.0.0/index.md#L42).

I'm proposing we consider removing it in https://github.com/commitizen/conventional-commit-types/pull/16, so I would appreciate if you could share thoughts there.
