### ISSUE TITLE
Support Breaking Change 

### ISSUE THREAD

**Issue by emilyrohrbough** [commitizen/conventional-commit-types#22]
Add support for Breaking Change PRs. Currently we are working around this with `chore(breaking)` however we'd like to format our titles like `breaking change:` or `breaking` similar to the docs outlined [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type) or even (major version bump`.

**Comment by AndersDJohnson** [comment]
@emilyrohrbough Thanks for filing this issue! I would recommend following the guidance from the Conventional Commits specification (https://www.conventionalcommits.org/en/v1.0.0/#examples), which give us a few options for breaking changes:
1. Include `BREAKING CHANGE: ` in the body or footer section of your full commit message.
2. Include a `!` after the scope and subject, e.g., `feat!: whatever` or `!feat(something): whatever`.

I hope these syntaxes are also supported by a lot of other tooling in this ecosystem.
Let us know if neither of these work for you.
