### ISSUE TITLE
Add gitmoji acceptance

### ISSUE THREAD

**Issue by jeankev** [commitizen/conventional-commit-types#24]
Hello, good job !

have you ever considered adding gitmoji ? (https://gitmoji.dev/)
example:
♻️ for type: - refactor
📝 for type: - docs
...

**Comment by AndersDJohnson** [comment]
@jeankev Thanks for raising this issue! It's a cool idea, but seems like it would reduce usability for users having to type those emojis out manually in some workflows. I don't know that introducing emojis would be appreciated by the general community in general.

Per this project README, we are pretty closely aligned with Angular conventions (https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type), and we'll likely stay that way.

However, as listed in our README, many tools should allow you to define your own types package or list of types where you could do this, e.g., https://github.com/conventional-changelog-archived-repos/validate-commit-msg#types. A fork of this project would be acceptable as well, and I'm happy to link to that from our README if you create one as an alternative for people.
