### ISSUE TITLE
suggestion; add enh / enhancement

### ISSUE THREAD

**Issue by smeijer** [commitizen/conventional-commit-types#9]
We have `feat` for *"a new feature"* and `fix` for *"a bug fix"*. But what when we `improve` the user experience of an existing feature? Shouldn't that be `enh` or `enhancement`?

`refactor` focusses too much on the code. So I feel like some commits don't really fit the suggested types.

**Comment by AndersDJohnson** [comment]
@smeijer Thanks for the suggestion. I think we'll try to track the more standard Angular commit message conventions. Do you know how they handle this? In my interpretation, `feat` could include updates to an existing feature (new features for that feature). We could consider changing its description, if that would help.
